version: '3'

services:
  frontend:
    build: ./docker/frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd react && yarn start'
    ports:
      - '3000:3000'
    tty: true